import gradio as gr
import torch

# 1. Custom Module Imports
from src.models.custom_cnn import CustomDeepfakeDetector
from src.models.resnet_router import load_orientation_classifier
from src.preprocessing.standardize import vision_transform, rotate_image
from src.preprocessing.intensity_route import determine_sequence_type
from src.inference.detect_forgery import analyze_scan
from src.inference.generate_twins import synthesize_mri
from src.utils.logger import log_user_data

# 2. Setup & Load Models
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Load Orientation Classifier
model_orient, orientation_classes = load_orientation_classifier(device)

# Load Deepfake Detector
model_detect = CustomDeepfakeDetector()
# Import os locally just for the path check if needed, or move path logic to inference
import os 
detect_weights_path = os.path.join('saved_models', 'custom_cnn_detector.pth')
if os.path.exists(detect_weights_path):
    model_detect.load_state_dict(torch.load(detect_weights_path, map_location=device, weights_only=True))
model_detect = model_detect.to(device)
model_detect.eval()

# 3. Master Pipeline
def process_mri(img):
    if img is None:
        return None, "No image provided.", None

    img = img.convert('RGB')

    # Preprocessing & Routing
    contrast_label, mean_intensity = determine_sequence_type(img)
    img_tensor = vision_transform(img).unsqueeze(0).to(device)

    # Classification Inference (CNN & ResNet)
    verdict_dict, plane_label = analyze_scan(img_tensor, model_detect, model_orient, orientation_classes)

    pipeline_report = (
        f"🔍 SEQUENCE ANALYSIS: {contrast_label} (Mean Brightness: {mean_intensity:.1f})\n"
        f"🧭 ORIENTATION PREDICTION: {plane_label.capitalize()}"
    )

    # GAN Synthesis Inference
    synthetic_twin_img, error_msg = synthesize_mri(contrast_label, device)
    pipeline_report += error_msg

    # Logging
    log_user_data(img, synthetic_twin_img, f"{contrast_label}_{plane_label}")

    return verdict_dict, pipeline_report, synthetic_twin_img

# 4. UI
with gr.Blocks() as interface:
    gr.Markdown("# 🛡️ EPICS Comprehensive Deepfake MRI Pipeline")
    gr.Markdown("Upload a raw MRI scan. Use the rotate button to correct orientation if needed. The system will process it, determine its biological parameters, scan it for AI tampering using the Custom CNN, and generate a synthetic clone via the associated GAN. Data is logged locally in `user_uploads/`.")

    with gr.Row():
        with gr.Column():
            input_img = gr.Image(type="pil", label="1. Upload MRI Scan")
            rotate_btn = gr.Button("↻ Rotate Image 90°")
            submit_btn = gr.Button("Initialize AI Pipeline", variant="primary")

        with gr.Column():
            out_verdict = gr.Label(num_top_classes=2, label="2. Custom CNN Detector Verdict")
            out_report = gr.Textbox(label="3. Preprocessing Metadata", lines=3)
            out_twin = gr.Image(type="pil", label="4. Synthetic Twin (Generated by GAN)")

    rotate_btn.click(
        fn=rotate_image,
        inputs=input_img,
        outputs=input_img
    )

    submit_btn.click(
        fn=process_mri,
        inputs=input_img,
        outputs=[out_verdict, out_report, out_twin]
    )

if __name__ == "__main__":
    interface.launch(inbrowser=True)
